headers = {
    'Accept': '*/*',
    'Accept-Language': 'en-US',
    "Bnc-Location": "",
    "Bnc-Uuid": "",
    'Clienttype': "web",
    'Content-Type': 'application/json',
    'Csrftoken': '',
    'Device-Info': "",
    "Cache-Control": "no-cache",
    "Pragma": "no-cache",
    "Priority": "u=1, i",
    "Fvideo-Id": "",
    "Fvideo-Token": "",
    "Lang": "en",
    'Origin': 'https://www.binance.com',
    'Referer': 'https://www.binance.com/vi/game/tg/moon-bix',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
    "X-Growth-Token": ""
}
